### ISSUE TITLE
VirtualCursor.AutomaticallyShiftRowsUp is off-by-one.

### ISSUE THREAD

**Issue by TheCommieDuck** [Thraka/SadConsole#12]
(I'm using F#, so I don't have an easy test case).
If I make a window, say, 10x10 - then write 9 rows of 10 characters, all is good.

If VirtualCursor.AutomaticallyShiftRowsUp = true and I try to write 10 rows, the first 9 rows are all shifted up one - the top row is lost, and the bottom row of the console is not drawn to.

Is this intended behaviour or just off-by-one?

**Comment by Thraka** [comment]
Posssssibly.. I'm not sure though. Can you show me some code? From memory (a lot of code was written years ago so various parts of the engine I'm out of touch with) with automatic shift I think the bottom line would end up being blank because as soon as you reach the end of the line, it shifts, which makes you have a single blank line. I'm pretty sure I use this in the ansi parser and it works ok, but there still could be a bug some where.

**Comment by Thraka** [comment]
I checked the code and it seems correct. However, I may have a bug in the part that processes a linefeed character. Are you using those?

**Comment by TheCommieDuck** [comment]
member self.Print(world : World.World) = 
        do self.VirtualCursor.Position <- Point (0, 0)
        [1..(fst size)] |> List.iter (fun x ->
            [1..(snd size)] |> List.iter (fun y ->
                do self.VirtualCursor.Print (world.Item (x, y)).glyph |> ignore
            ))

Is what I'm currently using.

>the bottom line would end up being blank because as soon as you reach the end of the line, it shifts, which makes you have a single blank line.

This is what I presume is happening after sleeping on it.

Not using linefeeds, though.

**Comment by Thraka** [comment]
OK I just replicated what you see and it is indeed correct. When you print on the last cell of a row, the cursor moves forward one space. If the cursor is now outside of the edge of the console, it's moved down one row and back to the left. However, if we were on the last row, we cannot move DOWN so it creates a new row for you.

Few things you can do:

1. `self.VirtualCursor.AutomaticallyShiftRowsUp = false`
2. Instead of using the cursor, you can actually print directly to the console data without a cursor managing position for you: `self.CellData.Print` or `self.CellData.SetCharacter`

**Comment by TheCommieDuck** [comment]
![image](https://cloud.githubusercontent.com/assets/832540/12404613/e61fe0da-be34-11e5-9a8f-a6f2d2b3734c.png)

Top portion, all rows drawn, Shift off.

![image](https://cloud.githubusercontent.com/assets/832540/12404624/0297ce80-be35-11e5-821f-b456ff3b2f06.png)

Top portion, all rows drawn, Shift on.

![image](https://cloud.githubusercontent.com/assets/832540/12404656/42f13de0-be35-11e5-98c9-781d5d4d98a8.png)

Top portion, all rows drawn except the last character of the 2nd last row (i.e. the cursor isn't shifted down).

I've been using `AutomaticallyShiftRowsUp = false`; didn't realise there was a `self.CellData.SetCharacter` - that sounds like a much better idea. Thank you!

**Comment by Thraka** [comment]
The virtual cursor was created to emulate a real console when you need to, like for the ansi parser or a command prompt console. Otherwise it's just easier to stuff the data directly into the surface. :smile: 

In your pictures above, are you trying to say things are not where they should go?

**Comment by TheCommieDuck** [comment]
Yep - it was trying to show that it's just when the virtual cursor hits that new line. Which, after discovering it's not the only/necessarily the best way to write to the console, is fixed. So it was intended behaviour after all. :p
