### ISSUE TITLE
helper method to print multi-line string in console

### ISSUE THREAD

**Issue by INeedAUniqueUsername** [Thraka/SadConsole#147]
Here is a helper method that I wrote for convenience. It prints a string containing multiple lines, ensuring that all lines begin on the same `x` position. The current Print() method apparently handles newlines improperly, so I think this method would be useful as an core feature.
```
public static void PrintLines(this SadConsole.Console console, int x, int y, string lines, Color? foreground = null, Color? background = null, SpriteEffects? mirror = null) {
	foreach (var line in lines.Replace("\r\n", "\n").Split('\n')) {
		console.Print(x, y, line, foreground, background, mirror);
		y++;
	}
}
```

**Comment by Thraka** [comment]
Currently the `surface.Print` type of statement is just a data blast of characters into the surface buffer. THe `console.Cursor.Print` uses the cursor object and does a lot of prediction and makes your print look like nice text. For example, it will check for spaces to determine if a word would be split between two lines and then moves the word down to the next line as a whole.

With how 7.0 is being designed, I wonder if I could actually move the cursor to the surface instead of just a console..

**Comment by Thraka** [comment]
I did look into this and the Cursor object already uses SurfaceBase as the host which means it can be created and attached to any drawing object in the system. However, only `Console` has it predefined. I think this is an acceptable design. Since you can create a view (subset view) of an existing surface with 7.0, you can easily block off the x column for use with the cursor or even with normal printing.

7.0 code looks something like this:

```csharp
var subSurface = existingConsoleOrSurface.GetViewSurface(new Rectangle(10, 10, 10, 10));
subSurface.Print(0, 0, "This is a string that is shared between both views. It will be positioned at 10,10 on the original surface and at position 0,0 in the view");
```

**Comment by Thraka** [comment]
Thank you for the suggestion though :) keep them coming!
