### ISSUE TITLE
ProcessMouse with BorderConsole

### ISSUE THREAD

**Issue by mc-lep** [Thraka/SadConsole#258]
Hello,

I'm not sure if this as issue or a misunderstand.

When adding borders to a console like in the sample  BorderedConsole.cs, the received state in the method ProcessMouse of the console contains wrong values for property CellPosition.

It seems like the ProcessMouse is onlt called when the mouse is outside the boundaries of the console.
If I remove the BorderComponent everything is fine. 

Kind regards,

Ferrero

**Comment by Thraka** [comment]
Can you share some more information? What version of SadConsole are you using? If the v9 beta, which host? Can you share some quick code about how you attached the bordered console? I have a few border console types throughout various samples 😄

**Comment by mc-lep** [comment]
Sure, I am using the v9 version with monogame host.
I've attached a zip with sample showing the issue. 
The bordered console prints the CellPosition and the WordCellPosition to show the issue I am facing.

[RFNet.zip](https://github.com/Thraka/SadConsole/files/6057316/RFNet.zip)

**Comment by Thraka** [comment]
@mc-lep I checked this out. It's not a bug. What is happening is you're overlaying the border console around the parent console. It "looks" like you've positioned it "behind" because it's a border, but in reality you actually have this console on top of the parent (since it's a child). So this console ends up processing the mouse instead of its parent. You need to disable the mouse when you create it:

```csharp
_borderConsole.UseMouse = false;
```
