### ISSUE TITLE
Calling InvokeClick() of a button from a keyboard shortcut doesn't change its state.

### ISSUE THREAD

**Issue by RychuP** [Thraka/SadConsole#306]
As per title. Example at https://github.com/RychuP/SadExperiments/blob/master/SadExperiments/Pages/GoRogueLineAlgorithms.cs (try pressing 1-4 and/or clicking buttons).

**Comment by Chris3606** [comment]
Tracked this through the source code....

This appears to be because [ButtonBase.InvokeClick()](https://github.com/Thraka/SadConsole/blob/620ca7a7838fb9e176e20de6a2c197868ea35f2e/SadConsole/UI/Controls/ButtonBase.cs#L65) simply calls `OnClicked()` which just invokes the `Clicked` event.  The state change is actually triggered by code in [ControlBase.ProcessMouse](https://github.com/Thraka/SadConsole/blob/620ca7a7838fb9e176e20de6a2c197868ea35f2e/SadConsole/UI/Controls/ControlBase.cs#L383) (it calls `OnLeftMouseClicked`, which ultimately calls `DetermineState`.

One cannot simply call `DetermineState after calling `InvokeClick`, since that function determines its state based on cached values which are not updated if `ProcessMouse` isn't called.  In order to emulate the state change you get with click, I simply set the appropriate state value before then called determine state, something like this:

```CS
public void InvokeClick()
{
    bool old = MouseState_IsMouseOver;
    MouseState_IsMouseOver = true;
    OnClick();
    DetermineState();
    MouseState_IsMouseOver = old;
}
```

This at least results in the ending state of the button being "Selected", as you would get with an actual mouse click.  Not sure if this is the correct fix though.

FWIW I definitely expected `InvokeClick()` to select the button just looking at the API, simply because the documentation for that method states "Simulates a mouse click on the button."  If it intentionally omits the state change, perhaps that could be clarified in the documentation?

**Comment by Chris3606** [comment]
Sorry, my test was being affected by some code external to the example... The correct emulation of the behavior would be to set `IsFocused`, I think:

```CS
public void InvokeClick()
{
    IsFocused = true;
    OnClick();
    DetermineState();
}
```

**Comment by Chris3606** [comment]
Small addendum; this still would leave the fact that the _parent_ console isn't focused automatically; this _technically_ solves that:
```CS
public void InvokeClick()
{
    // Fancy check to make sure Parent, Parent.Host, and Parent.Host.ParentConsole are all non-null
    if (Parent is { Host.ParentConsole: { } })
        Parent.Host.ParentConsole.IsFocused = true;
    
    IsFocused = true;
    OnClick();
    DetermineState();
}
```

There might be a better solution though.

**Comment by Thraka** [comment]
The goal of `InvokeClick` is to trigger the game logic you've tied to the button. I think it's better to keep it simple and at that. If you wanted focus associated with it, then you can simply focus the button and console from the same code you used to call `InvokeClick`, if that's your desired behavior.

Besides a **focused** state, you would never see another one since it all happens within a single frame. For example, you wouldn't be able to visualize the **down** then **up** states.

If memory serves me correctly, I think you can mark the control as dirty to get it determine the state and redraw.

**Comment by Thraka** [comment]
@RychuP Thoughts on this?

**Comment by RychuP** [comment]
I am actually in the process of familiarizing myself with the whole Controls system. There's quite a lot going on there behind the scenes. I'm intrigued.

I think whoever calls the InvokeClick() on a button expects the final result of the method to be the same as if it was an actual click with the mouse. That doesn't include visualization of the actual mouse down and up states. Just invoking the click logic and leaving the button in the focused state with the appropriate theme state applied.

**Comment by Thraka** [comment]
@RychuP You know, I could add a focus boolean to the method that focuses before or after the click is invoked (to match what the control does via the mouse)

```csharp
button.InvokeClick(true); // focuses the control
button.InvokeClick(); // doesn't focus
```

**Comment by RychuP** [comment]
Sounds good.
