### ISSUE TITLE
Add support for sorting `IScreenObject` in the parents collection

### ISSUE THREAD

**Issue by Thraka** [Thraka/SadConsole#310]
Sort would have to be a manual operation. Automatic sort shouldn't be supported, as it may change the entire behavior of a collection of objects. The user has full control to either keep the order as they added the children, or invoke a sort.

**Comment by Chris3606** [comment]
Quick thought on this; there is an asymptotic notation difference in the algorithms required to _insert_ an element at an arbitrary position which keeps the list sorted, vs sorting an unsorted list.  Namely, the worst case of finding the proper position to insert an item at in an already sorted list then inserting it there, will always be better than the worst-case for a sort algorithm.

Therefore, if the API only supports the user inserting an item then calling a sort function, this could limit a user from writing very efficient code.  If the API also supports inserting an item at an arbitrary index in the list, the problem is solved since the user could just implement "find the proper index and insert" to maintain sorting.
