### ISSUE TITLE
hiding system mouse cursor

### ISSUE THREAD

**Issue by erikyuzwa** [Thraka/SadConsole#79]
My humble apologies, but I seem to be unable to hide the system mouse cursor. I'm tracking the mouse position via an updating `GameObject`, but am still seeing the system mouse cursor. 

Is there an `Engine` flag or call to hide this?

**Comment by Thraka** [comment]
This is something controlled by MonoGame.

```
SadConsole.Engine.MonoGameInstance.IsMouseVisible = false;
```

**Comment by erikyuzwa** [comment]
most excellent - nice and simple like I was hoping.

**Comment by Thraka** [comment]
You may have to promote your mouse drawing (when you draw the GameObject) to the Engine.Draw (can't remember the name exactly) hook instead of doing it in a console. Otherwise, when you popup a window, it will be drawn on top of your text-mouse.

Also, check the Window static type, there are some helpers for popups there (like message box or choice boxes, stuff like that)

**Comment by erikyuzwa** [comment]
hmm thanks!! 
I think that's perhaps definitely a concern with something "more advanced" than my current demo. I did update my codebase to show/hide the system mouse when a modal dialog is shown, and so far everything is rendering ok (including z-ordering). But that's useful info to remember...
