### ISSUE TITLE
Memory leak in Demo program

### ISSUE THREAD

**Issue by QuickC** [Thraka/SadConsole#99]
When running the demo program, memory usage is stable until you create a new "world", part of the createRandomWorldTask = new Task<BasicSurface>(GenerateWorld); code.

Each new world increases memory usage by 25 to 50 mb.  something seems to be preventing the old world from being GC'd

**Comment by Thraka** [comment]
Hrm I'll have to look at this. Sorry, I thought I had responded to you, thanks.

**Comment by Thraka** [comment]
I ran a diagnostics in visual studio with the release version and I couldn't really detect anything. The reference counts and memory usage between generations was the same. The memory usage of the app though fluctuates over time. I think .NET holds on to memory for you (especially when you create 500,000 object instances such as the random generated world. 

But no leaks detected. If I left the game running long enough and forced the GC to collect at various times (or sometimes without forcing it) the app would collect normally and lower in usage. It kept going back to the same amount of memory each time. I tried 4 generations and compared each memory capture to each other.

**Comment by QuickC** [comment]
Andy,

As far as TUI’s I’ve found on the web, yours seems to be the only one remotely modern and that functions as stated.  I would like to use your Console for text based UI’s with open GL on a raspberry pie.  But first I would like to build modern ribbon based menus, and revise the controls appearance.  Maybe you could give me an idea of what I will need to touch (file wise) to achieve such a goal.

[cid:image003.png@01D417AB.D1623DF0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Thraka** [comment]
I really need to document the control system in a tutorial or something to show how to create new controls and things. As part of my 7.0 revision, I'm looking at how to redesign it to be easier to use. Right now the theme system really only handles foreground/background color for a control based on state (mouse over, mouse click down, etc) and I want to redo that so that the theme really dictates the drawing of a control, this means the theme/control stuff is going to change quite a bit soon.

---

I think looking at the button system would help you understand the controls a bit.

* [ControlBase](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Controls/ControlBase.cs) basic functions all controls use and must implement.

* [ButtonBase](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Controls/Button.cs#L14) which defines the things shared by all buttons.

* [Button](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Controls/Button.cs#L189) which defines the normal button control.

Controls really have 2 main components

1. The `DetermineAppearance` method  
This method is called at various times (like when the mouse moves over the control) to determine if the state of the control has changed. If it has changed, then various visual settings are changed, and the controls i marked `IsDirty = true`

2. The `Compose` method  
If `IsDirty == true`, then this method does the actual drawing of the control to the backing text surface of the control. This uses whatever graphical settings/appearance stuff set by the `DetermineAppearance` method. This effectively sets the visual state of the control.

If a control is visually updated (by the `OnComposed` callback defined by each control when it is redrawn) the `ControlsConsole` hosting the control will also be redrawn. The `ControlsConsole` uses a `ControlsConsoleRenderer` to draw the console and each control visual state to the console's texture object which is eventually reflected to the screen.

**Comment by QuickC** [comment]
If there is a way I can help when your start you work, let me know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
